Uno: controls.c File Reference
controls.c File Reference
#include "controls.h"
#include "pile.h"
#include "rules.h"
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
Functions
void generatePile ()
Génération de la pile de cartes.
Players addPlayer (Players P)
Ajoute un joueur à la liste des joueurs.
Players removePlayer (Players P, Player N)
Supprime un joueur de la liste des joueurs.
void showPlayers (Players P)
Affiche la liste des joueurs.
void takeCard (Player P)
Ajoute une carte au joueur passé en argument.
Player getPlayer (Players P, int id)
Renvoie le joueur correspondant à l'ID en argument.
Player getPlayerFromPosition (Players P, int pos)
Renvoie le joueur situé à l'index passée en argument.
int zeroCard (Player P)
Indique si le joueur P n'a plus de cartes.
void plusX (Player P, int n)
Fait piocher X carte(s) au joueur P.
void deleteCard (Player P, int card)
Supprime une carte de la main d'un joueur.
Variables
int ID = 0
ID des joueurs.
Function Documentation
addPlayer()
Players addPlayer (Players P)
Ajoute un joueur à la liste des joueurs.
Prend une liste de joueurs en paramètre. Crée un nouveau joueur et l'initialise avec un ID unique, un nombre de cartes défini, et une main aléatoire. Le joueur créé est ajouté à la liste des joueurs. prout.
Definition at line 55 of file controls.c.
References Player::cartes, ID, Player::id, NBCARTES, Players::next, Players::player, pop(), and Player::totalCard.
Referenced by jouer(), main(), and play().
 {
     Player newPlayer = malloc(sizeof(Player)); assert(newPlayer);
     newPlayer->id = ID++;
     newPlayer->totalCard = NBCARTES;
     newPlayer->cartes = malloc(sizeof(struct Carte) * NBCARTES); assert(newPlayer->cartes);
     for (int i = 0; i < NBCARTES; i++)
         newPlayer->cartes[i] = pop();
     Players p = malloc(sizeof(struct Players)); assert(p);
     p->player = newPlayer;
     p->next = P;
     return p;
 }
deleteCard()
void deleteCard (Player P, int card)
Supprime une carte de la main d'un joueur.
Supprime une carte du joueur P. card : numéro de carte à supprimer. Alloue de la mémoire pour un nouveau tableau de cartes plus petit de 1 carte. Parcourt les cartes du joueur P, si le numéro de la carte actuelle n'est pas égal à card, ajoute la carte au nouveau tableau. Enfin, change l'ancien tableau de cartes pour le nouveau, et décrémente le nombre total de cartes de P.
Definition at line 192 of file controls.c.
References Player::cartes, Carte::num, and Player::totalCard.
Referenced by jouer(), main(), and play().
 {
     Carte *newCard = malloc(sizeof(struct Carte) * (P->totalCard - 1)); assert(newCard);
     for (int i = 0, j = 0, v = 0; i < P->totalCard; i++)
     {
         if (P->cartes[i].num != card)
             newCard[j++] = P->cartes[i];
         else
             if (v) newCard[j++] = P->cartes[i];
             else v++;
     }
     free(P->cartes);
     P->cartes = newCard;
     P->totalCard--;
 }
generatePile()
void generatePile (void)
Génération de la pile de cartes.
Génère toutes les cartes du UNO dans la pile et mélange la pile. Les numéros de 0 à 9 correspondent aux cartes chiffres de 0 à 9, et celles de 10 à 14 aux malus.
10 : passer le tour du prochain joueur.
11: changement de sens de jeu.
12: +2 (le prochain joueur pioche 2 cartes).
13: changement de couleur.
14: +4 (le joueur choisit une nouvelle couleur et le prochain joueur pioche 4 cartes).
Definition at line 24 of file controls.c.
References B, Carte::color, G, M, M4, Carte::num, PILE_MAX, push(), R, shuffle(), and Y.
Referenced by main().
 {
     int i = 0, j = 0;
     Carte cR, cB, cG, cY, cM, cM4;
     cR.color = R; cB.color = B; cG.color = G; cY.color = Y; cM.color = M; cM.color = M4;
     while (i != PILE_MAX)
     {
         if (j <= 14)
         {
             if (j < 13)
             {
                 cR.num = cB.num = cG.num = cY.num = j;
                 push(cR); push(cB); push(cG); push(cY);
                 if (j > 0) { push(cR); push(cB); push(cG); push(cY); }
             }
             else
             {
                 cM.num = j; cM4.num = j;
                 push(cM); push(cM); push(cM4); push(cM4);
             }
         }
         i++; j++;
     } shuffle(); //mélange
 }
getPlayer()
Player getPlayer (Players P, int id)
Renvoie le joueur correspondant à l'ID en argument.
Prend la liste des joueur et un id en paramètres. Retourne le joueur dont l'ID est passé en paramètre. Parcourt la liste des joueurs. Si l'ID passé en paramètre correspond à celui du joueur courant, retourne ce joueur, sinon passe au joueur suivant.
Definition at line 136 of file controls.c.
References Player::id, Players::next, and Players::player.
Referenced by jouer(), and main().
 {
     Players tmp = P; Player p;
     while (tmp != NULL)
     {
         p = tmp->player;
         if (p->id == id) return p;
         tmp = tmp->next;
     }
     return NULL;
 }
getPlayerFromPosition()
Player getPlayerFromPosition (Players P, int pos)
Renvoie le joueur situé à l'index passée en argument.
Prend en paramètre la liste des joueurs et un entier représentant une position. Retourne un joueur depuis sa position dans la structure. Parcourt la liste des joueurs en icrémentant au fur et à mesure une variable i jusqu'à pos, et retourne le joueur actuel lorque i vaut pos.
Definition at line 153 of file controls.c.
References Players::next, and Players::player.
Referenced by main().
 {
     Players tmp = P; Player p;
     int i = 0;
     while (tmp != NULL)
     {
         p = tmp->player;
         if (i == pos) return p;
         tmp = tmp->next;
         i++;
     }
     return NULL;
 }
plusX()
void plusX (Player P, int n)
Fait piocher X carte(s) au joueur P.
Fait piocher X carte(s) au joueur P. n : carte à piocher en fonction de plusieurs +2 / +4 posés. Initialise i à 0. Tant que i est différent de n, fait piocher une carte au joueur P et incrément i.
Definition at line 179 of file controls.c.
References Player::id, and takeCard().
Referenced by applyEffect(), and jouer().
 {
     int i = 0;
     while (i != n) { takeCard(P); i++; }
     printf("Le joueur %d pioche %d cartes.\n", P->id, n);
 }
removePlayer()
Players removePlayer (Players P, Player N)
Supprime un joueur de la liste des joueurs.
Prend la liste des joueurs et un joueur à supprimer en paramètres. Si le joueur courant dans la liste est le joueur à supprimer, libère la mémoire allouée au joueur et renvoie la nouvelle liste des joueurs, sinon parcourt la liste des joueurs jusqu'à trouver le joueur à supprimer. Renvoie la liste des joueurs inchangée si le joueur à supprimer n'est pas trouvé.
Definition at line 78 of file controls.c.
References Player::cartes, Players::next, and Players::player.
Referenced by jouer(), main(), and play().
 {
     if (P->player == N)
     {
         Players r = P->next;
         free(P->player->cartes); free(N); free(P);
         return r;
     }
     Players courant = P, prec = P;
     while (courant != NULL)
     {
         if (courant->player == N)
         {
             prec->next = courant->next;
             free(courant->player->cartes); free(N); free(courant);
             return P;
         }
         prec = courant;
         courant = courant->next;
     }
     return P;
 }
showPlayers()
void showPlayers (Players P)
Affiche la liste des joueurs.
Prend la liste des joueurs en paramètre. Tant que le joueur courant ne vaut pas NULL, affiche son ID, son nombre de cartes et ses cartes, et passe au joueur suivant.
Definition at line 106 of file controls.c.
References Player::cartes, Player::id, Players::next, Carte::num, Players::player, and Player::totalCard.
Referenced by main().
 {
     Players tmp = P;
     while (tmp != NULL)
     {
         Player p = tmp->player;
         printf("ID : %d \nCartes:\n", p->id);
         printf("total -> %d\n", p->totalCard);
         for (int i = 0; i < p->totalCard; i++)
             printf("%d\n", p->cartes[i].num);
         tmp= tmp->next; printf("\n");
     }
 }
takeCard()
void takeCard (Player P)
Ajoute une carte au joueur passé en argument.
Prend en paramètre un joueur. Permet de faire piocher une carte au joueur passé en paramètre. Réalloue de la mémoire pour les cartes du joueur, et y ajoute la carte du dessus de la pioche.
Definition at line 126 of file controls.c.
References Player::cartes, pop(), and Player::totalCard.
Referenced by jouer(), main(), plusX(), and selectIndexCard().
 {
     P->cartes = realloc(P->cartes, sizeof(struct Carte) * (P->totalCard + 1)); assert(P->cartes);
     P->cartes[P->totalCard++] = pop();
 }
zeroCard()
int zeroCard (Player P)
Indique si le joueur P n'a plus de cartes.
Retourne 1 si le joueur n'a plus de cartes, 0 sinon.
Definition at line 170 of file controls.c.
References Player::totalCard.
Referenced by jouer().
 {
     return P->totalCard < 1;
 }
Variable Documentation
ID
int ID = 0
ID des joueurs.
Definition at line 10 of file controls.c.
Referenced by addPlayer().