Uno: pile.h File Reference
pile.h File Reference
Functions
void push (Carte v)
Ajoute une carte à la pile.
Carte pop (void)
Retourne la carte au-dessus de la pile, et la retire.
int empty (void)
Retourne 1 si la pile est vide, 0 sinon.
void shuffle (void)
Mélange la pile.
Function Documentation
empty()
int empty (void)
Retourne 1 si la pile est vide, 0 sinon.
Retourne 1 si la pile est vide, 0 sinon.
Definition at line 24 of file pile.c.
References _haut.
                 {
     return _haut < 0;
 }
pop()
Carte pop (void)
Retourne la carte au-dessus de la pile, et la retire.
Retourne la carte au-dessus de la pile, et la retire.
Definition at line 19 of file pile.c.
References _haut.
Referenced by addPlayer(), getCard(), jouer(), and takeCard().
                 {
     return _pile[_haut--];
 }
push()
void push (Carte v)
Ajoute une carte à la pile.
Ajoute une carte à la pile.
Definition at line 14 of file pile.c.
References _haut.
Referenced by generatePile(), getCard(), jouer(), and play().
                    {
     _pile[++_haut] = v;
 }
shuffle()
void shuffle (void)
Mélange la pile.
Mélange la pile.
Definition at line 29 of file pile.c.
References PILE_MAX.
Referenced by generatePile(), getCard(), jouer(), and play().
 {
     srand(time(NULL));
     if (PILE_MAX > 1)
     {
         size_t i;
         for (i = 0; i < PILE_MAX - 1; i++)
         {
           size_t j = i + rand() / (RAND_MAX / (PILE_MAX - i) + 1);
           Carte t = _pile[j];
           _pile[j] = _pile[i];
           _pile[i] = t;
         }
     }
 }